version: '3.9'

services:
  db:
    image: postgres:15
    container_name: kltn_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - kltn_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kltn_icd10_dev
    command: sh run.sh
    volumes:
      - .:/app           # ✅ mount code để hot reload trong dev
      - /app/__pycache__ # tránh pycache copy về máy host
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis_icd10_dev
      ENABLE_PYDEVD: true
    depends_on:
      - db
      - redis_icd10_dev
    restart: always
    env_file:
      - .env
    networks:
      - kltn_network
  
  redis_icd10_dev:
    image: redis:7
    container_name: redis_icd10_dev
    ports:
      - "6379:6379"
    networks:
      - kltn_network
    volumes:
      - redis_data_file_dev:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data_dev:
  redis_data_file_dev:

networks:
  kltn_network:
